version: "2"
services:
  store:
    build: ./data
    ports:
    - "4000:4000"
    depends_on:
    - mongo
  server:
    build: .
    ports:
    - "3000:3000"
    depends_on:
    - mongo
  mongo:
    image: mongo
    restart: always
    ports:
    - "27017:27017"